name: tutorial_kanban
version: 0.0.1
author: Marco Jakob <majakob@gmx.ch>
description: Tutorial about how to build a Kanban-Style Todo Board with Dart.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  script_inliner: any
transformers:
- script_inliner