name: tutorial_kanban
version: 0.0.2
author: Marco Jakob <majakob@gmx.ch>
description: Tutorial about how to build a Kanban-Style Todo Board with Dart.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  dart_to_js_script_rewriter:
    git: https://github.com/sethladd/dart_to_js_script_rewriter
transformers:
- dart_to_js_script_rewriter